openapi: 3.0.3
info:
  title: Crawlab API
  description: API for Crawlab, an open-source distributed web crawler admin platform
  version: 0.7.0

servers:
  - url: "{scheme}://{host}:{port}/api"
    description: Default API server
    variables:
      scheme:
          enum:
          - http
          - https
          default: http
      host:
          default: localhost
      port:
          default: "8080"

components:
  schemas:
    # Type schemas
    ObjectId:
      $ref: './components/schemas/types/ObjectId.yaml'

    # Entity schemas
    Error:
      $ref: './components/schemas/entities/Error.yaml'
    Success:
      $ref: './components/schemas/entities/Success.yaml'
    SuccessWithData:
      $ref: './components/schemas/entities/SuccessWithData.yaml'
    SuccessWithList:
      $ref: './components/schemas/entities/SuccessWithList.yaml'
    Pagination:
      $ref: './components/schemas/entities/Pagination.yaml'

    # Model schemas
    User:
      $ref: './components/schemas/models/User.yaml'
    Token:
      $ref: './components/schemas/models/Token.yaml'
    Node:
      $ref: './components/schemas/models/Node.yaml'
    Project:
      $ref: './components/schemas/models/Project.yaml'
    Spider:
      $ref: './components/schemas/models/Spider.yaml'
    Task:
      $ref: './components/schemas/models/Task.yaml'
    TaskStat:
      $ref: './components/schemas/models/TaskStat.yaml'
    Schedule:
      $ref: './components/schemas/models/Schedule.yaml'
    DependencyConfig:
      $ref: './components/schemas/models/DependencyConfig.yaml'
    DependencyRepo:
      $ref: './components/schemas/models/DependencyRepo.yaml'
    NotificationSetting:
      $ref: './components/schemas/models/NotificationSetting.yaml'
    NotificationRequest:
      $ref: './components/schemas/models/NotificationRequest.yaml'
    NotificationChannel:
      $ref: './components/schemas/models/NotificationChannel.yaml'
    NotificationAlert:
      $ref: './components/schemas/models/NotificationAlert.yaml'
    Role:
      $ref: './components/schemas/models/Role.yaml'
    DataCollection:
      $ref: './components/schemas/models/DataCollection.yaml'
    DataField:
      $ref: './components/schemas/models/DataField.yaml'
    Database:
      $ref: './components/schemas/models/Database.yaml'
    Environment:
      $ref: './components/schemas/models/Environment.yaml'
    Git:
      $ref: './components/schemas/models/Git.yaml'
    GitRef:
      $ref: './components/schemas/models/GitRef.yaml'
    MetricTrend:
      $ref: './components/schemas/models/MetricTrend.yaml'

  securitySchemes:
    BearerAuth:
      $ref: './components/securitySchemes/BearerAuth.yaml'

  parameters:
    PageParam:
      $ref: './components/parameters/PageParam.yaml'
    SizeParam:
      $ref: './components/parameters/SizeParam.yaml'
    AllParam:
      $ref: './components/parameters/AllParam.yaml'
    StatsParam:
      $ref: './components/parameters/StatsParam.yaml'
    IdParam:
      $ref: './components/parameters/IdParam.yaml'

security:
  - BearerAuth: []

paths:
  # Authentication paths
  /login:
    $ref: './paths/authentication/login.yaml'
  /tokens:
    $ref: './paths/authentication/tokens.yaml'

  # Node paths
  /nodes:
    $ref: './paths/nodes/nodes.yaml'
  /nodes/{id}:
    $ref: './paths/nodes/nodes_id.yaml'
  /nodes/{id}/metrics/time-range:
    $ref: './paths/nodes/nodes_id_metrics_time-range.yaml'
  /nodes/{id}/metrics/current:
    $ref: './paths/nodes/nodes_id_metrics_current.yaml'

  # Spider paths
  /spiders:
    $ref: './paths/spiders/spiders.yaml'
  /spiders/{id}:
    $ref: './paths/spiders/spiders_id.yaml'
  /spiders/{id}/run:
    $ref: './paths/spiders/spiders_id_run.yaml'
  /spiders/{id}/files/list:
    $ref: './paths/spiders/spiders_id_files_list.yaml'
  /spiders/{id}/files/get:
    $ref: './paths/spiders/spiders_id_files_get.yaml'
  /spiders/{id}/files/save:
    $ref: './paths/spiders/spiders_id_files_save.yaml'
  /spiders/{id}/results:
    $ref: './paths/spiders/spiders_id_results.yaml'
  /spiders/{id}/files/info:
    $ref: './paths/spiders/spiders_id_files_info.yaml'
  /spiders/{id}/files/save/batch:
    $ref: './paths/spiders/spiders_id_files_save_batch.yaml'
  /spiders/{id}/files/save/dir:
    $ref: './paths/spiders/spiders_id_files_save_dir.yaml'
  /spiders/{id}/files/rename:
    $ref: './paths/spiders/spiders_id_files_rename.yaml'
  /spiders/{id}/files/copy:
    $ref: './paths/spiders/spiders_id_files_copy.yaml'
  /spiders/{id}/files/export:
    $ref: './paths/spiders/spiders_id_files_export.yaml'
  /spiders/{id}/files/delete:
    $ref: './paths/spiders/spiders_id_files_delete.yaml'

  # Project paths
  /projects:
    $ref: './paths/projects/projects.yaml'
  /projects/{id}:
    $ref: './paths/projects/projects_id.yaml'

  # Task paths
  /tasks:
    $ref: './paths/tasks/tasks.yaml'
  /tasks/{id}:
    $ref: './paths/tasks/tasks_id.yaml'
  /tasks/{id}/restart:
    $ref: './paths/tasks/tasks_id_restart.yaml'
  /tasks/{id}/cancel:
    $ref: './paths/tasks/tasks_id_cancel.yaml'
  /tasks/{id}/logs:
    $ref: './paths/tasks/tasks_id_logs.yaml'
  /tasks/run:
    $ref: './paths/tasks/tasks_run.yaml'

  # Schedule paths
  /schedules:
    $ref: './paths/schedules/schedules.yaml'
  /schedules/{id}:
    $ref: './paths/schedules/schedules_id.yaml'

  # Git paths
  /gits:
    $ref: './paths/gits/gits.yaml'
  /gits/{id}:
    $ref: './paths/gits/gits_id.yaml'
  /gits/{id}/clone:
    $ref: './paths/gits/gits_id_clone.yaml'
  /gits/{id}/branches:
    $ref: './paths/gits/gits_id_branches.yaml'
  /gits/{id}/branches/current:
    $ref: './paths/gits/gits_id_branches_current.yaml'
  /gits/{id}/branches/remote:
    $ref: './paths/gits/gits_id_branches_remote.yaml'
  /gits/{id}/branches/checkout:
    $ref: './paths/gits/gits_id_branches_checkout.yaml'
  /gits/{id}/branches/checkout/remote:
    $ref: './paths/gits/gits_id_branches_checkout_remote.yaml'
  /gits/{id}/changes:
    $ref: './paths/gits/gits_id_changes.yaml'
  /gits/{id}/pull:
    $ref: './paths/gits/gits_id_pull.yaml'
  /gits/{id}/pull/ws:
    $ref: './paths/gits/gits_id_pull_ws.yaml'
  /gits/{id}/push/ws:
    $ref: './paths/gits/gits_id_push_ws.yaml'
  /gits/{id}/files/diff:
    $ref: './paths/gits/gits_id_files_diff.yaml'
  /gits/{id}/commit:
    $ref: './paths/gits/gits_id_commit.yaml'
  /gits/{id}/push:
    $ref: './paths/gits/gits_id_push.yaml'
  /gits/{id}/logs:
    $ref: './paths/gits/gits_id_logs.yaml'
  /gits/{id}/files/list:
    $ref: './paths/gits/gits_id_files_list.yaml'
  /gits/{id}/files/get:
    $ref: './paths/gits/gits_id_files_get.yaml'
  /gits/{id}/files/save:
    $ref: './paths/gits/gits_id_files_save.yaml'
  /gits/{id}/spiders:
    $ref: './paths/gits/gits_id_spiders.yaml'

  # Dependencies paths
  /dependencies/settings:
    $ref: './paths/dependencies/settings.yaml'
  /dependencies/settings/{id}:
    $ref: './paths/dependencies/settings_id.yaml'
  /dependencies/configs/{language}:
    $ref: './paths/dependencies/configs_language.yaml'
  /dependencies/configs/{language}/versions:
    $ref: './paths/dependencies/configs_language_versions.yaml'
  /dependencies/configs/{language}/setups:
    $ref: './paths/dependencies/configs_language_setups.yaml'
  /dependencies/configs/{language}/setups/install:
    $ref: './paths/dependencies/configs_language_setups_install.yaml'
  /dependencies/configs/{language}/setups/uninstall:
    $ref: './paths/dependencies/configs_language_setups_uninstall.yaml'
  /dependencies/repos:
    $ref: './paths/dependencies/repos.yaml'
  /dependencies/repos/search:
    $ref: './paths/dependencies/repos_search.yaml'
  /dependencies/repos/versions:
    $ref: './paths/dependencies/repos_versions.yaml'
  /dependencies/repos/update:
    $ref: './paths/dependencies/repos_update.yaml'
  /dependencies/repos/install:
    $ref: './paths/dependencies/repos_install.yaml'
  /dependencies/repos/uninstall:
    $ref: './paths/dependencies/repos_uninstall.yaml'
  /dependencies/{id}/logs:
    $ref: './paths/dependencies/logs_id.yaml'
  /dependencies/spiders/{id}:
    $ref: './paths/dependencies/spiders_id.yaml'
  /dependencies/spiders/{id}/install:
    $ref: './paths/dependencies/spiders_id_install.yaml'

  # Notification paths
  /notifications/settings:
    $ref: './paths/notifications/settings.yaml'
  /notifications/settings/{id}:
    $ref: './paths/notifications/settings_id.yaml'
  /notifications/settings/{id}/enable:
    $ref: './paths/notifications/settings_id_enable.yaml'
  /notifications/settings/{id}/disable:
    $ref: './paths/notifications/settings_id_disable.yaml'
  /notifications/settings/{id}/requests:
    $ref: './paths/notifications/settings_id_requests.yaml'
  /notifications/channels:
    $ref: './paths/notifications/channels.yaml'
  /notifications/channels/{id}:
    $ref: './paths/notifications/channels_id.yaml'
  /notifications/requests:
    $ref: './paths/notifications/requests.yaml'

  # Database paths
  /databases:
    $ref: './paths/databases/databases.yaml'
  /databases/{id}:
    $ref: './paths/databases/databases_id.yaml'
  /databases/{id}/connection/test:
    $ref: './paths/databases/databases_id_connection_test.yaml'
  /databases/{id}/metadata:
    $ref: './paths/databases/databases_id_metadata.yaml'
  /databases/{id}/tables/metadata:
    $ref: './paths/databases/databases_id_tables_metadata.yaml'
  /databases/{id}/tables/metadata/get:
    $ref: './paths/databases/databases_id_tables_metadata_get.yaml'
  /databases/{id}/tables/create:
    $ref: './paths/databases/databases_id_tables_create.yaml'
  /databases/{id}/tables/modify:
    $ref: './paths/databases/databases_id_tables_modify.yaml'
  /databases/{id}/tables/drop:
    $ref: './paths/databases/databases_id_tables_drop.yaml'
  /databases/{id}/tables/rename:
    $ref: './paths/databases/databases_id_tables_rename.yaml'
  /databases/{id}/tables/data:
    $ref: './paths/databases/databases_id_tables_data.yaml'
  /databases/{id}/tables/data/get:
    $ref: './paths/databases/databases_id_tables_data_get.yaml'
  /databases/{id}/columns/types:
    $ref: './paths/databases/databases_id_columns_types.yaml'
  /databases/{id}/query:
    $ref: './paths/databases/databases_id_query.yaml'
  /databases/metrics:
    $ref: './paths/databases/databases_metrics.yaml'
  /databases/{id}/metrics/time-range:
    $ref: './paths/databases/databases_id_metrics_time-range.yaml'
  /databases/{id}/metrics/current:
    $ref: './paths/databases/databases_id_metrics_current.yaml'
  /databases/{id}/export/{type}:
    $ref: './paths/databases/databases_id_export_type.yaml'
  /databases/{id}/export/{type}/{exportId}:
    $ref: './paths/databases/databases_id_export_type_exportId.yaml'
  /databases/{id}/export/{type}/{exportId}/download:
    $ref: './paths/databases/databases_id_export_type_exportId_download.yaml'

  # Users paths
  /users:
    $ref: './paths/users/users.yaml'
  /users/{id}:
    $ref: './paths/users/users_id.yaml'
  /users/{id}/change-password:
    $ref: './paths/users/users_id_changepassword.yaml'
  /users/me:
    $ref: './paths/users/users_me.yaml'
  /users/me/change-password:
    $ref: './paths/users/users_me_changepassword.yaml'

  # Permissions paths
  /roles:
    $ref: './paths/permissions/roles.yaml'
  /roles/{id}:
    $ref: './paths/permissions/roles_id.yaml'

  # System paths
  /system-info:
    $ref: './paths/system/system-info.yaml'
  /stats:
    $ref: './paths/system/stats.yaml'
  /settings:
    $ref: './paths/system/settings.yaml'

  # Export paths
  /export/{type}:
    $ref: './paths/export/export_type.yaml'
  /export/{type}/{exportId}:
    $ref: './paths/export/export_type_exportId.yaml'
  /export/{type}/{exportId}/download:
    $ref: './paths/export/export_type_exportId_download.yaml'

tags:
  - name: Authentication
    description: Authentication related operations
  - name: Nodes
    description: Node management operations
  - name: Spiders
    description: Spider management operations
  - name: Projects
    description: Project management operations
  - name: Tasks
    description: Task management operations
  - name: Schedules
    description: Schedule management operations
  - name: Git
    description: Git integration operations
  - name: Dependencies
    description: Dependency management operations
  - name: Notifications
    description: Notification system operations
  - name: Database
    description: Database operations
  - name: Users
    description: User management operations
  - name: Permissions
    description: Role-based access control operations
  - name: System
    description: System management operations
  - name: Export
    description: Export operations
