get:
  operationId: getTaskById
  tags:
    - Tasks
  summary: Get task by ID
  parameters:
    - $ref: '../../components/parameters/IdParam.yaml'
  responses:
    '200':
      description: Task details
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../../components/schemas/entities/SuccessWithData.yaml'
              - type: object
                properties:
                  data:
                    $ref: '../../components/schemas/models/Task.yaml'
    '404':
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/entities/Error.yaml'
delete:
  operationId: deleteTaskById
  tags:
    - Tasks
  summary: Delete task by ID
  parameters:
    - $ref: '../../components/parameters/IdParam.yaml'
  responses:
    '200':
      description: Task deleted successfully
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/entities/Success.yaml'
    '404':
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/entities/Error.yaml' 