get:
  operationId: getDependencySetupListForLanguage
  tags:
    - Dependencies
  summary: Get dependency setup list for a language
  description: Get list of dependency setups for a specific language
  parameters:
    - name: language
      in: path
      required: true
      description: Programming language (python, node, etc.)
      schema:
        type: string
  responses:
    '200':
      description: Dependency setup list
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../../components/schemas/entities/SuccessWithList.yaml'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: object 